INSERT INTO BIKE_STATION (NAME) VALUES('PodoGaleria');
INSERT INTO BIKE_STATION (NAME) VALUES('PodoSzpital');
INSERT INTO BIKE_STATION (NAME) VALUES('PodoPestka');

INSERT INTO BIKE_STATION_SLOT_SET (FREE, BIKE_STATION_ID) VALUES(false, 1);
INSERT INTO BIKE_STATION_SLOT_SET (FREE, BIKE_STATION_ID) VALUES(false, 1);
INSERT INTO BIKE_STATION_SLOT_SET (FREE, BIKE_STATION_ID) VALUES(true, 1);
INSERT INTO BIKE_STATION_SLOT_SET (FREE, BIKE_STATION_ID) VALUES(true, 1);

INSERT INTO BIKE_STATION_SLOT_SET (FREE, BIKE_STATION_ID) VALUES(false, 2);
INSERT INTO BIKE_STATION_SLOT_SET (FREE, BIKE_STATION_ID) VALUES(false, 2);
INSERT INTO BIKE_STATION_SLOT_SET (FREE, BIKE_STATION_ID) VALUES(false, 2);
INSERT INTO BIKE_STATION_SLOT_SET (FREE, BIKE_STATION_ID) VALUES(false, 2);

INSERT INTO BIKE_STATION_SLOT_SET (FREE, BIKE_STATION_ID) VALUES(false, 3);
INSERT INTO BIKE_STATION_SLOT_SET (FREE, BIKE_STATION_ID) VALUES(false, 3);
INSERT INTO BIKE_STATION_SLOT_SET (FREE, BIKE_STATION_ID) VALUES(false, 3);
INSERT INTO BIKE_STATION_SLOT_SET (FREE, BIKE_STATION_ID) VALUES(true, 3);

INSERT INTO BIKE_STATION_BIKE_SET (SERIAL_NUMBER, BIKE_STATION_ID) VALUES('123456789NF', 1);
INSERT INTO BIKE_STATION_BIKE_SET (SERIAL_NUMBER, BIKE_STATION_ID) VALUES('Fh5698Q68DF', 1);

INSERT INTO BIKE_STATION_BIKE_SET (SERIAL_NUMBER, BIKE_STATION_ID) VALUES('159487263DeG', 2);
INSERT INTO BIKE_STATION_BIKE_SET (SERIAL_NUMBER, BIKE_STATION_ID) VALUES('SN548w5dd6s', 2);
INSERT INTO BIKE_STATION_BIKE_SET (SERIAL_NUMBER, BIKE_STATION_ID) VALUES('123456asd98', 2);
INSERT INTO BIKE_STATION_BIKE_SET (SERIAL_NUMBER, BIKE_STATION_ID) VALUES('5495dD6sGrh', 2);

INSERT INTO BIKE_STATION_BIKE_SET (SERIAL_NUMBER, BIKE_STATION_ID) VALUES('45RTgy5dSE6', 3);
INSERT INTO BIKE_STATION_BIKE_SET (SERIAL_NUMBER, BIKE_STATION_ID) VALUES('498fhGTXC23', 3);
INSERT INTO BIKE_STATION_BIKE_SET (SERIAL_NUMBER, BIKE_STATION_ID) VALUES('45fd5EHB123', 3);

INSERT INTO USER_TEMP (USER_NAME) VALUES('Parkin9');